apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/inventory-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - image: api
          name: api-c
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: api-claim0
            - mountPath: /app/node_modules
              name: api-claim1
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
        - name: api-claim1
          persistentVolumeClaim:
            claimName: api-claim1
status: {}
