apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/inventory-default: "true"
        io.kompose.service: client
    spec:
      containers:
        - image: client
          name: client-c
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          stdin: true
      restartPolicy: Always
status: {}
