version: "3.8"
services:
   mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb-myapp-1
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        MONGO_INITDB_ROOT_DATABASE: admin
        MONGODB_DB: ${MONGODB_DB}
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - app-network
   api:
    build: ./api
    container_name: api_c
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - DB_HOST=mongodb
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=admin
      - DB_PORT=27017
      - MONGO_URI=mongodb://mongodb:27017/products?authSource=admin
    ports:
      - '4000:4000'
    networks:
      - app-network
    links:
     - mongodb
   client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    stdin_open: true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge